@startuml

UN_PAID : 未支付
OPENED : 已开通
REFUND_AUDITING : 退款审核中
REFUND_SUCCEED : 退款成功
START : start
PAID : 已支付
START --> UN_PAID : CREATE
UN_PAID --> PAID : PAY
PAID --> OPENED : OPEN
PAID --> REFUND_AUDITING : REFUND_COMMIT
OPENED --> REFUND_AUDITING : REFUND_COMMIT
PAID --> [*] : CHECK
REFUND_AUDITING --> REFUND_SUCCEED : REFUND_PASS
state CHOICE_1 <<choice>>
REFUND_AUDITING --> CHOICE_1 : REFUND_DENNY
CHOICE_1 -[dashed]-> PAID : RollBackGuard
CHOICE_1 -[dashed]-> OPENED : default
@enduml